### ISSUE TITLE
using snappy problem

### ISSUE THREAD

**Issue by yakie** [ohos-rs/packages#1]
试了有点问题，安装说明安装之后oh_modules里有@ohos-rs的扩展包了，然后
import  {compressSync}  from '@ohos-rs/snappy'
显示有错误
Module '"../../../../../oh_modules/@ohos-rs/snappy"' has no exported member 'compressSync'. <tsCheck>
可以运行，执行const a = compressSync("hello world", { copyOutputData: false });
有异常

**Comment by richerfu** [comment]
Please make sure that you should install this package with your right module, which will use it. For example, if you want to use it with `entry` module, you should install it in `entry` folder.

And more, please provide your basic info, i can help you to solve this problem.
- Harmony API Version
- Platform(Mac/Windows)

**Comment by richerfu** [comment]
Actually, there's no issue with the recognition of API 9 installation on Windows, but this issue does occur on Mac. You can simply disregard it.

And for some ROM, some symbol are not supported, our goal is API11 and above.

I can install this package from API9 to API12, and i think it's must be some other reason curse it.

For older version, some ROM will get some error:` __emutls_get_address: symbol not found`. 
You can try it with `0.0.4`. 

I'll close this issue. If you have other error, you can report a new issue.
