### ISSUE TITLE
[BUG]我在使用argon2加密并加了盐的时候报错

### ISSUE THREAD

**Issue by Donny1996** [ohos-rs/packages#11]
如下代码报错：`Failed to get Buffer pointer and length on Options.salt`
```typescript
    const options: Options = {
      memoryCost: 4096,
      timeCost: 3,
      parallelism: 1,
      version: Version.V0x13,
      algorithm: this._algorithm,  // 2id
      outputLen: this._outputLen,  // 32
      salt: this._salt
    }
    try {
      const result: string = hashSync(value, options)   // 这里尝试取options.salt[0]是有值的
//...
```
salt的buffer是通过如下代码产生的：
```typescript
const textEncoder = new util.TextEncoder(encoding);
const result: Uint8Array = textEncoder.encodeInto(data);
buffer.from(result);
```
请问是我操作不对还是库的问题？

**Package & Version**
 - Package name: [e.g. @ohos-rs/bcrypt] @ohos-rs/argon2
 - Version [e.g. 0.0.4] 0.1.2

**NDK or IDE Version**
[e.g. Next beta.1,5.0.0.0] 26sp9

**To Reproduce**

**Expected behavior**
output encrypted message.

**Screenshots**

**Additional context**

**Comment by richerfu** [comment]
用字符串试下，buffer 应该是已知问题（系统实现问题）。系统的 buffer 传递到 native 侧会有问题

argon2 可能暂不支持字符串，稍晚点补齐

**Comment by richerfu** [comment]
依赖 Buffer 的能力太多，晚点看能否推动系统侧解决该问题。这个问题很早就跟系统提了 调用 napi_get_buffer_info会失败。

**Comment by richerfu** [comment]
Buffer 问题参考：https://ohos.rs/docs/more/buffer.html
已提审新版本。 0.1.3 @DonnyAo1996
