### ISSUE TITLE
在HarmonyOS中使用 报错 is not callable SourceCode

### ISSUE THREAD

**Issue by SuperGuo751** [ohos-rs/packages#2]
老师您好，我通过https://ohpm.openharmony.cn/#/cn/detail/@ohos-rs%2Fcrc32/v/0.0.2在HarmonyOS preview2及beta1使用都报错

按照文档编写代码
                         const strNumber = crc32("crc32c - test",0);
                         console.log('打印数据 === ' + strNumber.toString());
报错：
Error message:is not callable
SourceCode:
                        const newCrc32 = crc32("crc32c - test", 0);
                                         ^
                                         
控制台直接打印报错：
                        ReferenceError: crc32 is not defined

感谢老师提供的库，希望能尽快得到答复

**Comment by richerfu** [comment]
DP2和BETA1的镜像加载逻辑有更新，目前的包结构会导致动态链接库加载失败。如果需要使用的话，暂时的解决办法有以下两种：
1. 下载之后，可以把.so文件复制出来通过本地文件引用。
2. 使用源码构建，本地引用。

问题修复后，会提交新包。

@SuperGuo751

**Comment by SuperGuo751** [comment]
老师 我早晨尝试了几种方式 一直跑不通 您能帮助我一下吗

我把下载好的libs，拖动到 lss/下，包含index.d.ts 和 复制过来的 oh-package.json5

然后在lss的oh-package.json5中引如，在ets中调用报错：
> hvigor ERROR: Failed :entry:default@CompileArkTS... 
> hvigor ERROR: ArkTS Compiler Error
ERROR:  ArkTS:ERROR Failed to get a resolved OhmUrl for "hvigor_ignore__Users_vhall_vhall_open_sdk_harmony_OpenSDK_lss_libs_index.d.ts" imported by "/Users/vhall/vhall_open_sdk_harmony/OpenSDK/lss/src/main/ets/components/live/VHLivePlayer.ets". Please check whether the module which hvigor_ignore__Users_vhall_vhall_open_sdk_harmony_OpenSDK_lss_libs_index.d.ts belongs to is correctly configuredand the corresponding file name matches (case sensitive) 
COMPILE RESULT:FAIL {ERROR:2}
> hvigor ERROR: BUILD FAILED in 1 s 680 ms 


<img width="1142" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/7e4866a9-4f60-4183-978b-1ddd7f8fc8a4">

<img width="1101" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/e6c148b0-0827-49ec-a1f4-9d159a851931">

<img width="686" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/537a99e2-b1fe-4de8-9f70-19db816e90df">

**Comment by SuperGuo751** [comment]
老师您好，我这边拖出来的文件好像引用还是有问题
<img width="1230" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/f0f42d40-3c46-4434-8203-4e19c3aa2808">

**Comment by richerfu** [comment]
TS定义问题。按以下步骤操作即可：

1. 新建一个HAR目录（new module -> static library）选择支持native的版本
2. 将`crc32`目录下面的整体的`libs`文件夹复制到新建的HAR目录下
3. 将`index.d.ts`中内容复制到新建的har目录下的`cpp`文件夹中的`Index.d.ts`文件中
4. 引入该新建的har包。

@SuperGuo751

**Comment by SuperGuo751** [comment]
老师，我按照您的流程新建了个demo去测试也同样不行

<img width="1440" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/720082da-883a-4675-89d7-2d31d54e657e">

[Uploading MyApplication2.zip…]()

**Comment by richerfu** [comment]
为什么是`libtest.so`？不是`libcrc32.so`？

**Comment by SuperGuo751** [comment]
老师 我因为新创建的三方库叫test所以后面引入的时候就是了，这边又新创建了个crc32，并且才模块代码中进行测试，还是有这个问题

<img width="1440" alt="image" src="https://github.com/ohos-rs/packages/assets/13793874/6eb79bf8-6144-4cad-b485-e2d17808cac3">

**Comment by richerfu** [comment]
通过主仓库的二维码进群聊吧。

**Comment by richerfu** [comment]
0.0.3
