### ISSUE TITLE
无法使用，引入都用不了

### ISSUE THREAD

**Issue by yululu1998** [ohos-rs/packages#4]
import { genSalt } from '@ohos-rs/bcrypt'  通过这样引入方法都是undefined
具体是什么问题呢
可否跟华为内部进行共建呢

**Comment by richerfu** [comment]
请提供下你的开发者工具版本。
目前看 ohpm 的包管理太过于复杂难用，在 Next 正式发布前 建议自行构建引入。 @yululu1998 
另外华为共建这个，目前我这边没有能力去推动这个事情。

**Comment by richerfu** [comment]
相关包已适配开发者预览版，已提审

**Comment by richerfu** [comment]
如果使用开发者预览版本，请升级到 0.0.3 @yululu1998 
本仓库相关 package 都已经适配该版本，其余版本建议自行构建后使用。构建后使用还有问题请另外新建 ISSUE。

<img width="781" alt="image" src="https://github.com/ohos-rs/packages/assets/32590310/7bc60417-93a2-4f0b-a72e-c323d107ac6a">

**Comment by yululu1998** [comment]
可否提供demo 或者指导文档

**Comment by yululu1998** [comment]
@richerfu

**Comment by richerfu** [comment]
自行构建指导：https://juejin.cn/post/7372466344144437289
构建完成使用指导：https://juejin.cn/post/7368741477214486538
